--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/GabBiswajit/SuperItemsShop
build-by-default: true
branches:
  - main
projects:
  SuperItemsShop:
    path: ""
    lint: false
    libs:
      - src: ImJustNozell/libEco/libEco
        version: ^1.0
      - src: ImJustNozell/FormsUI/FormsUI
        version: ^1.0
