name: SuperItemsShop
main: Biswajit\SuperItems\SuperItemsShop
version: 2.0.1
api: 5.0.0
authors: ["Biswajit", "Nozell"]
softdepend: ["BedrockEconomy", "EconomyAPI"]

commands:
  sshop:
    description: "use to open SuperItemsShop"
    usage: "/sshop"
    permission: SuperItemsShop.cmd.use
permissions:
  SuperItemsShop.cmd.use:
    description: "Permission To Use /sshop Command"
    default: true
